/* Generated By:JavaCC: Do not edit this line. yaplConstants.java */
package yapl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface yaplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int OTHERCHAR = 7;
  /** RegularExpression Id. */
  int COMMENT = 8;
  /** RegularExpression Id. */
  int NEW = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int DECLARE = 12;
  /** RegularExpression Id. */
  int PROGRAM = 13;
  /** RegularExpression Id. */
  int BEGIN = 14;
  /** RegularExpression Id. */
  int END = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int ENDIF = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int CONST = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int ENDWHILE = 23;
  /** RegularExpression Id. */
  int RETURN = 24;
  /** RegularExpression Id. */
  int WRITE = 25;
  /** RegularExpression Id. */
  int READONLY = 26;
  /** RegularExpression Id. */
  int PROCEDURE = 27;
  /** RegularExpression Id. */
  int Type = 28;
  /** RegularExpression Id. */
  int PrimType = 29;
  /** RegularExpression Id. */
  int Literal = 30;
  /** RegularExpression Id. */
  int IDENT = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int STRING = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<OTHERCHAR>",
    "<COMMENT>",
    "\"new\"",
    "\"And\"",
    "\"Or\"",
    "\"Declare\"",
    "\"Program\"",
    "\"Begin\"",
    "\"End\"",
    "\"If\"",
    "\"Then\"",
    "\"Else\"",
    "\"EndIf\"",
    "\"While\"",
    "\"Const\"",
    "\"Do\"",
    "\"EndWhile\"",
    "\"Return\"",
    "\"Write\"",
    "\"Readonly\"",
    "\"Procedure\"",
    "<Type>",
    "<PrimType>",
    "<Literal>",
    "<IDENT>",
    "<NUMBER>",
    "<STRING>",
    "\"[\"",
    "\"]\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\".\"",
  };

}
